# Generated by Django 2.2.1 on 2019-10-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20191006_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default='24:00'),
        ),
    ]
