# Generated by Django 2.2.1 on 2019-10-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default='23:59'),
        ),
    ]
