# Generated by Django 2.2.1 on 2019-10-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20191006_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
    ]
