# Generated by Django 2.2.1 on 2019-10-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_appointment_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
    ]
