# Generated by Django 2.2.1 on 2019-10-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_remove_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
