# Generated by Django 2.2.1 on 2019-10-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20191006_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
